name: Jonathan Fontanez
description: Blogging about stuffs
meta_description: "Your New Jekyll Site, Blogging about stuffs"

aboutPage: true

markdown: redcarpet
highlighter: rogue
gems: [jekyll-paginate]
paginate: 20
baseurl: /
domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-55930909-2'
disqus: true
disqus_shortname: 'tato123githubio'

# Details for the RSS feed generator
url:            'http://your-blog-url.example.com'
author:         'Jonathan Fontanez'
authorTwitter:  '@jonfontanez'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
